file_exists "import-map.json"
file_exists "README.md"
file_exists "LICENSE.md"

file_exists "dist/highcharts.js"
file_exists "dist/highcharts-3d.js"
file_exists "dist/highcharts-gantt.js"
file_exists "dist/highcharts-more.js"
file_exists "dist/highmaps.js"
file_exists "dist/highstock.js"
dir_exists "dist/css"
dir_exists "dist/gfx"
dir_exists "dist/indicators"
dir_exists "dist/lib"
dir_exists "dist/modules"
dir_exists "dist/themes"
